# Generated by Django 5.2.4 on 2025-08-06 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_of_origin',
            field=models.ForeignKey(help_text="User's country of origin", null=True, on_delete=django.db.models.deletion.PROTECT, to='users.country'),
        ),
    ]
