# Generated by Django 5.2.4 on 2025-08-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_country_of_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='student',
            name='arrival_date',
            field=models.DateField(blank=True, help_text='Date the student arrived', null=True),
        ),
    ]
