# Generated by Django 5.2.4 on 2025-08-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_country_options_alter_student_arrival_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='users_stude_state_c41cf3_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='users_stude_guidanc_24b700_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='users_stude_in_pers_9d7e89_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guidance_needed',
        ),
        migrations.RemoveField(
            model_name='student',
            name='in_person_assistance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
    ]
