# Generated by Django 5.2.4 on 2025-08-23 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_student_users_stude_state_c41cf3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0, help_text='Current balance of the wallet in the smallest currency unit (e.g., cents)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the wallet was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the wallet was last updated')),
                ('user', models.OneToOneField(help_text='The user account associated with this wallet', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='Optional note or description for the transaction', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Current status of the transaction', max_length=10)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('membership_fee', 'Membership Fee'), ('donation', 'Donation')], help_text='Type of transaction (deposit, withdrawal, membership fee, donation)', max_length=20)),
                ('amount', models.BigIntegerField(help_text='Transaction amount in the smallest currency unit (e.g., cents)')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('online', 'Online Payment'), ('wallet', 'Wallet Balance')], default='online', help_text='Method used for this transaction (e.g., Cash, Cheque, Online Payment)', max_length=20)),
                ('related_project', models.CharField(blank=True, help_text='Project name if this transaction is linked to a specific project', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the transaction was created')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Deadline for completing this transaction', null=True)),
                ('membership', models.ForeignKey(blank=True, help_text='Related membership if this transaction is a membership fee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='users.membership')),
                ('wallet', models.ForeignKey(help_text='Wallet this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='finance_wal_user_id_b9d993_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['balance'], name='finance_wal_balance_acdcb7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'created_at'], name='finance_tra_wallet__d53539_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='finance_tra_status_0941b9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='finance_tra_type_390c6a_idx'),
        ),
    ]
